repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: double-quote-string-fixer
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-github-workflows
  - repo: local
    hooks:
    - id: test
      name: pytest
      entry: poetry run pytest --doctest-modules src tests
      language: system
      types: [python]
      pass_filenames: false
    - id: format-isort
      name: isort
      entry: poetry run isort src tests
      language: system
      types: [python]
    - id: format-black
      name: black
      entry: poetry run black --skip-string-normalization src tests
      language: system
      types: [python]
    - id: lint
      name: flake8
      entry: poetry run flake8 src tests
      language: system
      types: [python]
